# Generated by Django 5.1.15 on 2026-08-26 22:46

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.SlugField(max_length=255)),
                ('api_key', models.CharField(db_index=True, max_length=255, unique=True)),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('flag_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('MULTIVARIATE', 'Multivariate')], default='BOOLEAN', max_length=20)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='core_flags.environment')),
            ],
            options={
                'unique_together': {('environment', 'key')},
            },
        ),
        migrations.CreateModel(
            name='FlagOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='core_flags.featureflag')),
            ],
        ),
        migrations.CreateModel(
            name='StrategyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priority', models.IntegerField(default=0)),
                ('operator_logic', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', max_length=3)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core_flags.featureflag')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute', models.CharField(max_length=255)),
                ('operator', models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('IN_LIST', 'In List'), ('CONTAINS', 'Contains')], max_length=20)),
                ('value', models.JSONField()),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='core_flags.strategyrule')),
            ],
        ),
    ]
