# Generated by Django 6.1 on 2026-08-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureflag',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='flagoverride',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='flagoverride',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='flagoverride',
            index=models.Index(fields=['flag', 'cleared_at'], name='core_flags__flag_id_c73580_idx'),
        ),
    ]
