# Generated by Django 6.1 on 2026-09-18 03:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_flags', '0003_environment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyrule',
            name='rollout_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('percentage_allocation', models.IntegerField()),
                ('is_control', models.BooleanField(default=False)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core_flags.featureflag')),
            ],
            options={
                'unique_together': {('flag', 'name')},
            },
        ),
        migrations.AddField(
            model_name='strategyrule',
            name='rollout_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollout_rules', to='core_flags.variant'),
        ),
    ]
