# Generated by Django 6.1 on 2026-09-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_flags', '0004_strategyrule_rollout_percentage_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='operator',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('IN_LIST', 'In List'), ('CONTAINS', 'Contains'), ('PERCENTAGE_SPLIT', 'Percentage Split')], max_length=20),
        ),
    ]
