# Generated by Django 6.1 on 2026-08-29 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='orgmembership_role_valid',
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VIEWER', 'Viewer')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'VIEWER'])), name='orgmembership_role_valid'),
        ),
    ]
