# Generated by Django 6.1 on 2026-08-29 02:45

from django.conf import settings
from django.db import migrations, models


def viewer_to_user(apps, schema_editor):
    """
    Carry existing VIEWER rows over to USER.

    Without this the new CheckConstraint fails to validate against any row
    still holding the old value, and the rename lands as a broken deploy
    rather than a rename.
    """
    OrganizationMembership = apps.get_model("tenancy", "OrganizationMembership")
    OrganizationMembership.objects.filter(role="VIEWER").update(role="USER")


def user_to_viewer(apps, schema_editor):
    """Reverse of `viewer_to_user`, so the migration is genuinely reversible."""
    OrganizationMembership = apps.get_model("tenancy", "OrganizationMembership")
    OrganizationMembership.objects.filter(role="USER").update(role="VIEWER")


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_drop_organization_owner_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembership',
            name='orgmembership_role_valid',
        ),
        # Data first: the constraint added below rejects any surviving VIEWER.
        migrations.RunPython(viewer_to_user, user_to_viewer),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['ADMIN', 'USER'])), name='orgmembership_role_valid'),
        ),
    ]
