# Generated by Django 6.1 on 2026-09-03 22:50

from django.db import migrations, models

import tenancy.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('COMMUNITY', 'Community'), ('FREE', 'Free'), ('STARTER', 'Starter'), ('TEAM', 'Team')], default=tenancy.models.default_organization_plan, max_length=20),
        ),
    ]
