# Generated by Django 6.1 on 2026-09-29 16:14

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationIdentity',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('installation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='installation_identity_is_a_singleton')],
            },
        ),
    ]
