# Generated by Django 5.1.15 on 2026-08-26 23:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_flags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_hash', models.CharField(max_length=64)),
                ('result', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_logs', to='core_flags.featureflag')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SDKRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sdk_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sdk_type', models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('GO', 'Go')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdk_registrations', to='core_flags.environment')),
            ],
        ),
    ]
