# Generated by Django 6.1 on 2026-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_flags', '0002_alter_featureflag_options_alter_flagoverride_options_and_more'),
        ('sdk_api', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sdkregistration',
            constraint=models.UniqueConstraint(fields=('environment', 'sdk_type'), name='unique_sdk_registration_per_environment_and_type'),
        ),
    ]
