# Generated by Django 6.1 on 2026-09-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk_api', '0002_sdkregistration_unique_sdk_registration_per_environment_and_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdkregistration',
            name='sdk_type',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('GO', 'Go'), ('REACT', 'React'), ('VUE', 'Vue'), ('SOLID', 'Solid'), ('SVELTE', 'Svelte')], max_length=20),
        ),
    ]
