# Generated by Django 6.1 on 2026-09-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdk_api', '0005_evaluationlog_result_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdkregistration',
            name='sdk_type',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('JAVASCRIPT', 'JavaScript'), ('GO', 'Go'), ('REACT', 'React'), ('VUE', 'Vue'), ('SOLID', 'Solid'), ('SVELTE', 'Svelte'), ('OPENFEATURE_WEB', 'OpenFeature (web)')], max_length=20),
        ),
    ]
